"""Tests for the regime engine (HMM walk-forward + labels + BOCPD).

Everything here is OFFLINE and DETERMINISTIC. The feature frames are **synthetic**: they are generated by
`make_synthetic_features` from a seeded numpy Generator with three PLANTED regimes and one PLANTED shock
day, and they are not market data. They exist to check that the machinery recovers a structure that is
known by construction, not to make any claim about Brent.
"""

from __future__ import annotations

import collections
import importlib.util
import logging
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from engine.features import catalog as cat
from engine.regime import model as model_mod
from engine.regime.base import (
    LABEL_BACKWARDATION_HIGHVOL_GEO,
    LABEL_BULL_SQUEEZE,
    LABEL_CONTANGO_GLUT_DOWNTREND,
    LABEL_LOWVOL_RANGE,
    LABEL_SHOCK_CRASH,
    LABEL_TRANSITION,
    RegimeState,
)
from engine.regime.bocpd import bocpd_run_length, change_point_probability, expanding_standardise
from engine.regime.full import HISTORY_COLUMNS, FullRegimeModel
from engine.regime.labels import PROTOTYPES, STATE_LABELS, label_states, prob_column
from engine.regime.model import ConstantRegimeModel, make_regime_model

# --- synthetic world ---------------------------------------------------------------------------------
LOW = "low_vol_drift"
HIGH = "high_vol_backwardation_geo"
DOWN = "downtrend_contango"

TRUTH_TO_LABEL = {
    LOW: LABEL_LOWVOL_RANGE,
    HIGH: LABEL_BACKWARDATION_HIGHVOL_GEO,
    DOWN: LABEL_CONTANGO_GLUT_DOWNTREND,
}

# (mean, sd) per planted regime. Deliberately separable but overlapping at one sigma.
SPECS: dict[str, dict[str, tuple[float, float]]] = {
    LOW: {
        "ret1": (0.0002, 0.008),
        "ret21": (0.005, 0.012),
        "rv": (0.18, 0.015),
        "slope": (0.000, 0.004),
        "tsmom": (0.0, 0.30),
        "geo": (0.15, 0.03),
        "stocks": (0.000, 0.015),
    },
    HIGH: {
        "ret1": (0.0020, 0.032),
        "ret21": (0.045, 0.030),
        "rv": (0.55, 0.050),
        "slope": (0.080, 0.010),
        "tsmom": (1.2, 0.40),
        "geo": (0.85, 0.05),
        "stocks": (-0.060, 0.015),
    },
    DOWN: {
        "ret1": (-0.0024, 0.018),
        "ret21": (-0.050, 0.020),
        "rv": (0.30, 0.025),
        "slope": (-0.060, 0.008),
        "tsmom": (-1.2, 0.40),
        "geo": (0.20, 0.04),
        "stocks": (0.070, 0.015),
    },
}

_BLOCKS: list[tuple[str, int]] = [
    (LOW, 260),
    (HIGH, 200),
    (LOW, 180),
    (DOWN, 220),
    (HIGH, 190),
    (LOW, 240),
    (DOWN, 210),
    (HIGH, 200),
    (LOW, 230),
    (DOWN, 190),
    (LOW, 200),
    (HIGH, 180),
]
SHOCK_AT = 1600  # inside a HIGH block, far from any planted regime boundary
SHOCK_LEN = 15
QUIET_SLICES = [slice(1100, 1280), slice(1750, 1900)]  # inside single LOW blocks
N_ROWS = 2500


def _truth(n: int) -> list[str]:
    seq: list[str] = []
    while len(seq) < n:
        for name, length in _BLOCKS:
            seq += [name] * length
    return seq[:n]


def make_synthetic_features(n: int = N_ROWS, seed: int = 7, spread: float = 1.0) -> tuple[pd.DataFrame, pd.Series]:
    """SYNTHETIC feature frame with three planted regimes and one planted shock. Not market data.

    `spread` multiplies every standard deviation: spread=1 gives well separated regimes, a large spread
    makes them overlap so much that the filtered posterior is flat (used to test the transition rule).
    """
    rng = np.random.default_rng(seed)
    truth = _truth(n)
    keys = ("ret1", "ret21", "rv", "slope", "tsmom", "geo", "stocks")
    rows = {k: np.empty(n, dtype="float64") for k in keys}
    for i, name in enumerate(truth):
        spec = SPECS[name]
        for k in keys:
            mean, sd = spec[k]
            rows[k][i] = rng.normal(mean, sd * spread)
    # planted shock: one violent day plus a three-week aftermath of high vol and negative one-month return
    if 0 <= SHOCK_AT < n:
        rows["ret1"][SHOCK_AT] = -0.22
        end = min(n, SHOCK_AT + SHOCK_LEN)
        rows["ret21"][SHOCK_AT:end] -= 0.18
        rows["rv"][SHOCK_AT:end] += 0.45
    idx = pd.bdate_range("2014-01-01", periods=n)
    frame = pd.DataFrame(
        {
            cat.RET_1: rows["ret1"],
            cat.RET_21: rows["ret21"],
            cat.RV_YZ_21: np.maximum(rows["rv"], 0.02),
            cat.SLOPE_M1_M6: rows["slope"],
            cat.VRP: np.nan,  # all-NaN on purpose: exercises the "drop the empty column" path
            cat.TSMOM_63: rows["tsmom"],
            cat.GEO_INDEX: np.clip(rows["geo"], 0.0, 1.0),
            cat.CRUDE_STOCKS_VS_5Y: rows["stocks"],
        },
        index=idx,
    )
    return frame, pd.Series(truth, index=idx, name="planted")


FAST_CONFIG = {"min_obs": 200, "refit_every": 100, "n_states_range": (3,)}


@pytest.fixture(scope="module")
def synthetic() -> tuple[pd.DataFrame, pd.Series]:
    return make_synthetic_features()


@pytest.fixture(scope="module")
def fitted(synthetic: tuple[pd.DataFrame, pd.Series]) -> tuple[FullRegimeModel, pd.DataFrame, float]:
    frame, _ = synthetic
    model = FullRegimeModel()
    started = time.perf_counter()
    hist = model.history(frame)
    return model, hist, time.perf_counter() - started


# --- labels ----------------------------------------------------------------------------------------
def test_prototypes_cover_every_state_label() -> None:
    assert set(PROTOTYPES) == set(STATE_LABELS)
    assert LABEL_TRANSITION not in PROTOTYPES  # transition is produced by the model, never by a state


def test_label_states_precedence_rules() -> None:
    names = [cat.RET_21, cat.RV_YZ_21, cat.SLOPE_M1_M6, cat.TSMOM_63, cat.GEO_INDEX, cat.CRUDE_STOCKS_VS_5Y]
    means = np.array(
        [
            [-2.0, 2.4, 0.5, -1.5, 1.0, -0.2],  # crash: huge vol, deeply negative month
            [0.6, 1.4, 1.2, 0.9, 1.3, -0.8],  # backwardation + vol + geo
            [-0.9, 0.2, -1.2, -1.1, -0.2, 1.1],  # contango glut downtrend
            [1.1, 0.0, 0.9, 1.3, -0.1, -0.7],  # bull squeeze
            [0.0, -1.0, 0.0, 0.1, -0.5, 0.0],  # low-vol range
        ]
    )
    assert label_states(means, names) == [
        LABEL_SHOCK_CRASH,
        LABEL_BACKWARDATION_HIGHVOL_GEO,
        LABEL_CONTANGO_GLUT_DOWNTREND,
        LABEL_BULL_SQUEEZE,
        LABEL_LOWVOL_RANGE,
    ]


def test_label_states_rejects_shape_mismatch() -> None:
    with pytest.raises(ValueError, match="feature names"):
        label_states(np.zeros((2, 3)), [cat.RET_21, cat.RV_YZ_21])


# --- walk-forward HMM ------------------------------------------------------------------------------
def test_history_shape_and_columns(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    _, hist, _ = fitted
    assert list(hist.columns) == HISTORY_COLUMNS
    assert len(hist) == N_ROWS
    probs = hist[[prob_column(x) for x in STATE_LABELS]].to_numpy()
    assert (probs >= -1e-12).all()
    assert (probs.sum(axis=1) <= 1.0 + 1e-9).all()


def test_all_nan_feature_is_dropped(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    model, _, _ = fitted
    result = model.hmm.result
    assert result is not None
    assert cat.VRP in result.features_used  # selected...
    for fit in result.fits:  # ...but never estimated on, because it is empty in every training window
        assert cat.VRP not in fit.feature_names
    assert result.slope_missing is False


def test_walk_forward_recovers_planted_regimes(
    synthetic: tuple[pd.DataFrame, pd.Series], fitted: tuple[FullRegimeModel, pd.DataFrame, float]
) -> None:
    frame, truth = synthetic
    model, hist, _ = fitted
    details = model._details
    assert details is not None
    # Out-of-sample days only: the first training window is necessarily labelled in-sample.
    oos = ~details.warmup.to_numpy()
    # The planted shock aftermath is legitimately "Shock/crash", which is not one of the three planted
    # regime labels, so those days are excluded from the recovery share.
    shock = np.zeros(len(frame), dtype=bool)
    shock[SHOCK_AT : SHOCK_AT + SHOCK_LEN + 5] = True
    scored = oos & ~shock
    expected = truth.map(TRUTH_TO_LABEL).to_numpy()
    hit = hist[cat.REGIME_LABEL].to_numpy()[scored] == expected[scored]
    share = float(hit.mean())
    logging.getLogger(__name__).info("regime recovery share = %.4f on %d days", share, int(scored.sum()))
    print(f"\nplanted-regime recovery share: {share:.4f} on {int(scored.sum())} out-of-sample days")
    assert share >= 0.70, f"recovery share {share:.3f} below the 70% floor"


def test_planted_shock_is_flagged_as_a_transition(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    """The planted shock is handled by the change-point path, not by a dedicated HMM state.

    Fifteen shock days out of 2 500 never buy their own state: BIC refuses the extra k. That is the right
    outcome -- the detector fires, the model says "Transizione" and the allocator cuts risk -- while
    LABEL_SHOCK_CRASH is reserved for a crash that PERSISTS long enough to be a regime (the labelling rule
    itself is covered by `test_label_states_precedence_rules`).
    """
    _, hist, _ = fitted
    window = hist.iloc[SHOCK_AT : SHOCK_AT + 10]
    assert (window[cat.REGIME_LABEL] == LABEL_TRANSITION).any()
    assert (window[cat.REGIME_ID] == -1).any()
    assert float(window[cat.BOCPD_CP_PROB].max()) > 0.5


def test_state_id_keeps_its_label_across_refits(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    model, _, _ = fitted
    result = model.hmm.result
    assert result is not None
    assert len(result.fits) > 5  # several refit boundaries in the sample
    per_id: dict[int, set[str]] = collections.defaultdict(set)
    for fit in result.fits:
        for cid, label in zip(fit.canonical_ids, label_states(fit.means, fit.feature_names)):
            per_id[cid].add(label)
    bad = {cid: labels for cid, labels in per_id.items() if len(labels) > 1}
    assert not bad, f"canonical state ids changed meaning across refits: {bad}"


def test_two_states_may_share_a_label_and_probabilities_add(
    fitted: tuple[FullRegimeModel, pd.DataFrame, float],
) -> None:
    model, hist, _ = fitted
    result = model.hmm.result
    assert result is not None
    shared = None
    for fit in result.fits:
        labels = label_states(fit.means, fit.feature_names)
        counts = collections.Counter(labels)
        dup = [label for label, c in counts.items() if c > 1]
        if dup:
            shared = (fit, labels, dup[0])
            break
    assert shared is not None, "no fit assigned the same label to two states; cannot check the sum rule"
    fit, labels, label = shared
    rows = result.fit_date == fit.fit_date
    cids = [cid for cid, lb in zip(fit.canonical_ids, labels) if lb == label]
    direct = result.posteriors.loc[rows, cids].sum(axis=1)
    reported = hist.loc[rows, prob_column(label)]
    pd.testing.assert_series_equal(direct, reported, check_names=False, check_exact=True)


def test_warmup_is_the_first_training_window(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    model, _, _ = fitted
    details = model._details
    result = model.hmm.result
    assert details is not None and result is not None
    assert int(details.warmup.sum()) == model.hmm.min_obs
    assert details.warmup.iloc[: model.hmm.min_obs].all()
    assert not details.warmup.iloc[model.hmm.min_obs :].any()


def test_model_string_names_the_fit(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    model, _, _ = fitted
    details = model._details
    assert details is not None
    last = str(details.model.iloc[-1])
    assert last.startswith("hmm") and "-wf-" in last


# --- causality -------------------------------------------------------------------------------------
def test_history_is_byte_identical_when_future_rows_are_appended() -> None:
    """THE causality test: appending 200 future rows must not move a single past number."""
    long_frame, _ = make_synthetic_features(N_ROWS + 200)
    short_frame = long_frame.iloc[:N_ROWS]
    a = FullRegimeModel().history(short_frame)
    b = FullRegimeModel().history(long_frame).iloc[:N_ROWS]
    numeric = [c for c in HISTORY_COLUMNS if c != cat.REGIME_LABEL]
    assert np.array_equal(a[numeric].to_numpy(), b[numeric].to_numpy()), "past numbers changed"
    assert (a[cat.REGIME_LABEL].to_numpy() == b[cat.REGIME_LABEL].to_numpy()).all()


def test_posteriors_are_byte_identical_when_future_rows_are_appended() -> None:
    from engine.regime.hmm import WalkForwardHmm

    long_frame, _ = make_synthetic_features(900)
    a = WalkForwardHmm(**FAST_CONFIG).posteriors(long_frame.iloc[:700])
    b = WalkForwardHmm(**FAST_CONFIG).posteriors(long_frame)
    common = [c for c in a.columns if c in b.columns]
    assert np.array_equal(a[common].to_numpy(), b[common].to_numpy().take(range(700), axis=0))


def test_expanding_standardisation_is_causal() -> None:
    s = pd.Series(np.random.default_rng(3).normal(size=400))
    a = expanding_standardise(s.iloc[:300])
    b = expanding_standardise(s).iloc[:300]
    assert np.array_equal(a.to_numpy(), b.to_numpy())


def test_bocpd_is_causal() -> None:
    x = np.random.default_rng(11).normal(size=600)
    x[400:] += 4.0
    a = bocpd_run_length(x[:400])
    b = bocpd_run_length(x)[:400]
    assert np.array_equal(a, b)


# --- BOCPD -----------------------------------------------------------------------------------------
def test_bocpd_fires_on_the_planted_shock_and_stays_quiet(
    fitted: tuple[FullRegimeModel, pd.DataFrame, float],
) -> None:
    _, hist, _ = fitted
    cp = hist[cat.BOCPD_CP_PROB]
    near = cp.iloc[SHOCK_AT : SHOCK_AT + 10]
    assert float(near.max()) > 0.5, f"no change point within 10 days of the shock (max {near.max():.3f})"
    for sl in QUIET_SLICES:
        quiet = cp.iloc[sl]
        assert float(quiet.max()) < 0.5, f"false alarm on a stationary stretch ({quiet.max():.3f})"


def test_bocpd_probability_is_a_probability() -> None:
    frame, _ = make_synthetic_features(400)
    cp = change_point_probability(frame)
    assert cp.name == cat.BOCPD_CP_PROB
    assert ((cp >= 0.0) & (cp <= 1.0)).all()


def test_bocpd_max_combines_the_two_channels() -> None:
    frame, _ = make_synthetic_features(400)
    both = change_point_probability(frame, use_vol_channel=True)
    ret_only = change_point_probability(frame, use_vol_channel=False)
    assert (both >= ret_only - 1e-12).all()
    assert float((both - ret_only).max()) > 0.0  # the vol channel does contribute somewhere


def test_bocpd_runtime_10000_rows() -> None:
    x = np.random.default_rng(5).normal(size=10_000)
    started = time.perf_counter()
    out = bocpd_run_length(x)
    elapsed = time.perf_counter() - started
    print(f"\nBOCPD runtime: {elapsed:.2f}s for 10000 rows")
    assert out.shape == (10_000,)
    assert elapsed < 30.0, f"BOCPD took {elapsed:.1f}s for 10000 rows"


def test_history_runtime_2500_rows(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    _, _, elapsed = fitted
    print(f"\nFullRegimeModel.history runtime: {elapsed:.2f}s for {N_ROWS} rows")
    assert elapsed < 90.0, f"history() took {elapsed:.1f}s for {N_ROWS} rows"


# --- transition rule -------------------------------------------------------------------------------
def test_change_point_forces_transition(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    _, hist, _ = fitted
    hot = hist[hist[cat.BOCPD_CP_PROB] > 0.5]
    assert len(hot) > 0
    assert (hot[cat.REGIME_LABEL] == LABEL_TRANSITION).all()
    assert (hot[cat.REGIME_ID] == -1).all()


def test_transition_when_probabilities_are_flat() -> None:
    """Overlapping regimes => flat posterior => "Transizione" with the underlying distribution reported."""
    frame, _ = make_synthetic_features(500, spread=8.0)
    model = FullRegimeModel(FAST_CONFIG)
    hist = model.history(frame)
    tail = hist.iloc[FAST_CONFIG["min_obs"] :]
    assert float(tail[cat.REGIME_CONF].min()) < model.min_confidence
    flat = tail[(tail[cat.REGIME_CONF] > 0.0) & (tail[cat.REGIME_CONF] < model.min_confidence)]
    assert len(flat) > 0, "the overlapping frame produced no low-confidence day"
    assert (flat[cat.REGIME_LABEL] == LABEL_TRANSITION).all()
    assert (flat[cat.REGIME_ID] == -1).all()


def test_transition_when_confidence_is_below_the_threshold() -> None:
    frame, _ = make_synthetic_features(500)
    # An unsatisfiable threshold: no regime can ever pass it, which is the brief's "nessun regime supera la
    # soglia di confidenza" case. The planted regimes are so separable that any threshold <= 1 is passed.
    strict = FullRegimeModel({**FAST_CONFIG, "min_confidence": 1.0 + 1e-9})
    hist = strict.history(frame)
    tail = hist.iloc[FAST_CONFIG["min_obs"] :]
    assert (tail[cat.REGIME_LABEL] == LABEL_TRANSITION).all()
    assert (tail[cat.REGIME_ID] == -1).all()
    state = strict.infer(frame, _utc(frame.index[-1]))
    assert state.label == LABEL_TRANSITION
    assert state.regime_id == -1
    assert state.is_transition
    # the underlying distribution is still reported
    assert state.probabilities and abs(sum(state.probabilities.values()) - 1.0) < 1e-6
    assert state.confidence == pytest.approx(max(state.probabilities.values()))


def test_reported_regimes_respect_the_thresholds(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    """A row that names a regime must clear BOTH gates; a transition row must fail at least one."""
    model, hist, _ = fitted
    named = hist[hist[cat.REGIME_LABEL] != LABEL_TRANSITION]
    assert len(named) > 0
    assert (named[cat.REGIME_CONF] >= model.min_confidence).all()
    assert (named[cat.BOCPD_CP_PROB] <= model.cp_threshold).all()
    assert (named[cat.REGIME_ID] >= 0).all()
    trans = hist[hist[cat.REGIME_LABEL] == LABEL_TRANSITION]
    failed = (trans[cat.REGIME_CONF] < model.min_confidence) | (trans[cat.BOCPD_CP_PROB] > model.cp_threshold)
    assert failed.all()
    # a uniform posterior over 3 states peaks at 1/3, well below the default threshold
    assert model.min_confidence > 1.0 / 3.0


def test_infer_matches_history_row(fitted: tuple[FullRegimeModel, pd.DataFrame, float]) -> None:
    model, hist, _ = fitted
    original, _ = make_synthetic_features()
    day = original.index[-1]
    state = model.infer(original, _utc(day))
    assert isinstance(state, RegimeState)
    assert state.label == hist[cat.REGIME_LABEL].iloc[-1]
    assert state.confidence == pytest.approx(float(hist[cat.REGIME_CONF].iloc[-1]))
    assert state.change_point_prob == pytest.approx(float(hist[cat.BOCPD_CP_PROB].iloc[-1]))
    assert state.model.startswith("hmm")
    assert state.approx is False
    assert cat.RET_21 in state.features_used
    assert state.to_dict()["label"] == state.label  # serialisable


def test_infer_before_the_first_row_is_a_transition() -> None:
    frame, _ = make_synthetic_features(300)
    model = FullRegimeModel(FAST_CONFIG)
    state = model.infer(frame, _utc(frame.index[0] - pd.Timedelta(days=30)))
    assert state.is_transition
    assert state.label == LABEL_TRANSITION
    assert state.confidence == 0.0


# --- curve-slope fallback and approximation flag ---------------------------------------------------
def test_slope_fallback_to_m1_m2() -> None:
    frame, _ = make_synthetic_features(400)
    frame = frame.rename(columns={cat.SLOPE_M1_M6: cat.SLOPE_M1_M2})
    model = FullRegimeModel(FAST_CONFIG)
    model.history(frame)
    result = model.hmm.result
    assert result is not None
    assert cat.SLOPE_M1_M2 in result.features_used
    assert result.slope_missing is False


def test_slope_missing_sets_the_approx_flag() -> None:
    frame, _ = make_synthetic_features(400)
    frame = frame.drop(columns=[cat.SLOPE_M1_M6])
    model = FullRegimeModel(FAST_CONFIG)
    model.history(frame)
    result = model.hmm.result
    assert result is not None
    assert result.slope_missing is True
    assert cat.SLOPE_M1_M6 not in result.features_used
    state = model.infer(frame, _utc(frame.index[-1]))
    assert state.approx is True


def test_approx_flag_follows_the_active_fit() -> None:
    """A window where the slope column exists but is empty is as approximate as one without the column."""
    frame, _ = make_synthetic_features(500)
    frame[cat.SLOPE_M1_M6] = np.where(np.arange(len(frame)) >= 300, frame[cat.SLOPE_M1_M6], np.nan)
    model = FullRegimeModel(FAST_CONFIG)
    model.history(frame)
    details = model._details
    result = model.hmm.result
    assert details is not None and result is not None
    assert result.slope_missing is False  # the column is not empty across the whole frame...
    assert result.fits[0].slope_missing is True  # ...but it is empty in the first training window
    assert result.fits[-1].slope_missing is False
    assert bool(details.approx.iloc[FAST_CONFIG["min_obs"]]) is True
    assert bool(details.approx.iloc[-1]) is False
    assert model.infer(frame, _utc(frame.index[-1])).approx is False


def test_too_few_observations_yields_no_fit() -> None:
    frame, _ = make_synthetic_features(100)
    model = FullRegimeModel(FAST_CONFIG)
    hist = model.history(frame)
    assert (hist[cat.REGIME_LABEL] == LABEL_TRANSITION).all()
    assert (hist[cat.REGIME_ID] == -1).all()
    assert (hist[cat.REGIME_CONF] == 0.0).all()
    assert model.infer(frame, _utc(frame.index[-1])).probabilities == {}


# --- persistence -----------------------------------------------------------------------------------
def test_save_and_load_round_trip(tmp_path: Path) -> None:
    frame, _ = make_synthetic_features(500)
    model = FullRegimeModel(FAST_CONFIG)
    first = model.history(frame)
    path = model.save(tmp_path / "regime.pkl")
    assert path.exists()
    restored = FullRegimeModel.load(path)
    assert restored.hmm.fit_cache  # fitted parameters came back
    second = restored.history(frame)
    pd.testing.assert_frame_equal(first, second)


def test_save_file_and_load_file_warm_an_existing_model(tmp_path: Path) -> None:
    """The names the live runner duck-types (`save_file` / `load_file`) must work on an existing model."""
    frame, _ = make_synthetic_features(500)
    source = FullRegimeModel(FAST_CONFIG)
    expected = source.history(frame)
    path = source.save_file(tmp_path / "models" / "regime.pkl")
    warm = FullRegimeModel(FAST_CONFIG)
    warm.load_file(path)
    assert warm.hmm.fit_cache
    pd.testing.assert_frame_equal(warm.history(frame), expected)


def test_load_rejects_a_foreign_pickle(tmp_path: Path) -> None:
    import pickle

    bad = tmp_path / "bad.pkl"
    bad.write_bytes(pickle.dumps({"version": 999}))
    with pytest.raises(ValueError, match="regime cache"):
        FullRegimeModel.load(bad)


# --- fallback model and factory --------------------------------------------------------------------
def test_constant_regime_model() -> None:
    frame, _ = make_synthetic_features(50)
    model = ConstantRegimeModel()
    assert model.name == "constant-transition"
    assert model.fit(frame) is None
    state = model.infer(frame, _utc(frame.index[-1]))
    assert state.label == LABEL_TRANSITION
    assert state.regime_id == -1
    assert state.confidence == 0.0
    assert state.probabilities == {}
    assert state.is_transition
    hist = model.history(frame)
    assert list(hist.columns) == HISTORY_COLUMNS
    assert (hist[cat.REGIME_LABEL] == LABEL_TRANSITION).all()
    assert (hist[cat.REGIME_CONF] == 0.0).all()


def test_make_regime_model_returns_the_full_model() -> None:
    model = make_regime_model({"min_obs": 300})
    assert isinstance(model, FullRegimeModel)
    assert model.hmm.min_obs == 300


def test_make_regime_model_falls_back_without_hmmlearn(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(model_mod, "hmmlearn_available", lambda: False)
    model = make_regime_model({})
    assert isinstance(model, ConstantRegimeModel)


def test_make_regime_model_falls_back_when_construction_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    def boom(_config: object) -> object:
        raise RuntimeError("synthetic failure")

    monkeypatch.setattr(model_mod, "FullRegimeModel", boom)
    model = make_regime_model({})
    assert isinstance(model, ConstantRegimeModel)


def test_make_regime_model_honours_an_explicit_constant_request() -> None:
    assert isinstance(make_regime_model({"model": "constant-transition"}), ConstantRegimeModel)


# --- optional smoke test on the real fixture (added by another agent) ------------------------------
def _fixture_available() -> bool:
    """Cheap check (no import, no I/O beyond a stat) used by the skipif marker."""
    if importlib.util.find_spec("engine.data.fixtures") is None:
        return False
    return (Path(__file__).parent / "fixtures" / "market_data").exists()


def _real_features() -> pd.DataFrame | None:
    """Build the feature frame from the captured market-data fixture, or None when it is not there."""
    try:
        fixtures = importlib.import_module("engine.data.fixtures")
    except ImportError:
        return None
    loader = next(
        (
            getattr(fixtures, name)
            for name in ("fixture_market_data", "load_fixture_market_data", "load_market_data", "market_data")
            if callable(getattr(fixtures, name, None))
        ),
        None,
    )
    if loader is None:
        return None
    try:
        md = loader()
        from engine.features.builder import FullFeatureBuilder

        asof = pd.Timestamp(md.prices.index[-1]).tz_localize("UTC") + pd.Timedelta(days=1)
        return FullFeatureBuilder().build(md, asof.to_pydatetime())
    except Exception:  # pragma: no cover - the fixture API is owned by another module
        return None


@pytest.mark.skipif(not _fixture_available(), reason="tests/fixtures/market_data + engine.data.fixtures not available")
def test_real_fixture_smoke() -> None:
    frame = _real_features()
    if frame is None:  # pragma: no cover - the fixture API is owned by another module
        pytest.skip("engine.data.fixtures does not expose a usable market-data loader")
    model = FullRegimeModel()
    hist = model.history(frame)
    y2026 = hist.loc[hist.index >= "2026-01-01", cat.REGIME_LABEL]
    if len(y2026) == 0:  # pragma: no cover - fixture may end earlier
        pytest.skip("the fixture does not reach 2026")
    counts = y2026.groupby(y2026.index.to_period("M")).value_counts()
    print("\n2026 monthly regime label counts (real fixture):")
    print(counts.to_string())


def _utc(day: pd.Timestamp) -> datetime:
    """Settlement timestamp (UTC) of a tz-naive trading date, as `infer` expects."""
    from engine.core.timeutil import settlement_ts

    return settlement_ts(pd.Timestamp(day).date())
